name: GitHub Pages Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/deploy.yml

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Build & Deploy
    permissions:
      contents: write
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: docs/.vitepress/dist